#### Create a program to implement the working of simple RNN - prediction of next letter of the word HELLO

In [ ]:
import tensorflow as tf
import numpy as np 
from tensorflow.keras.layers import SimpleRNN, Dense 
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential

In [31]:
text = "Hello"
char = sorted(set(text))
print(char)
char_to_index = {c:i for i,c in enumerate (char)}
index_to_text = {i:c for c,i in char_to_index.items()}
print(char_to_index)
print(index_to_text)


['H', 'e', 'l', 'o']
{'H': 0, 'e': 1, 'l': 2, 'o': 3}
{0: 'H', 1: 'e', 2: 'l', 3: 'o'}


In [19]:
input_char=text[:-1]
target_char = text[1:]
print(input_char)
print(target_char)

Hell
ello


In [ ]:
input_index=[char_to_index[c] for c in input_char]
target_index = [char_to_index[c]for c in target_char]
print(input_index)
print(target_index)

[0, 1, 2, 2]
[1, 2, 2, 3]


In [41]:
X = to_categorical(input_index,num_classes=len(char))
print(X)
print(X.shape)
X = np.reshape(X,(X.shape[0],1,X.shape[1]))
X

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]]
(4, 4)


array([[[1., 0., 0., 0.]],

       [[0., 1., 0., 0.]],

       [[0., 0., 1., 0.]],

       [[0., 0., 1., 0.]]], dtype=float32)

In [42]:
y = to_categorical(target_index, num_classes=len(char))

In [55]:
model = Sequential()
model.add(SimpleRNN(32, input_shape=(1, len(char)), return_sequences=False))
model.add(Dense(len(char), activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

model.fit(X, y, epochs=500)

Model: "sequential_12"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_18 (SimpleRNN)   (None, 32)                1184      
                                                                 
 dense_11 (Dense)            (None, 4)                 132       
                                                                 
Total params: 1,316
Trainable params: 1,316
Non-trainable params: 0
_________________________________________________________________
Epoch 1/500
1/1 [==============================] - 3s 3s/step - loss: 1.3947 - accuracy: 0.5000
Epoch 2/500
1/1 [==============================] - 0s 18ms/step - loss: 1.3845 - accuracy: 0.5000
Epoch 3/500
1/1 [==============================] - 0s 26ms/step - loss: 1.3744 - accuracy: 0.5000
Epoch 4/500
1/1 [==============================] - 0s 18ms/step - loss: 1.3643 - accuracy: 0.5000
Epoch 5/500
1/1 [==============================] - 0s 36m

In [ ]:
chars = char
def predict_next_letter(char):
    input_idx = char_to_index[char]
    input_onehot = to_categorical([input_idx], num_classes=len(chars))
    input_onehot = np.reshape(input_onehot, (1, 1, len(chars)))
    prediction = model.predict(input_onehot,verbose=False)
    predicted_index = np.argmax(prediction)
    return index_to_text[predicted_index]

print("Predictions:")
for c in input_char:
    print(f"{c} → {predict_next_letter(c)}")


Predictions:
prediction :  [[0.0057298  0.9764583  0.01327573 0.00453616]]  args :  1
H → e
prediction :  [[0.00103208 0.00833505 0.9793896  0.01124329]]  args :  2
e → l
prediction :  [[0.00340941 0.00572802 0.4990067  0.49185595]]  args :  2
l → l
prediction :  [[0.00340941 0.00572802 0.4990067  0.49185595]]  args :  2
l → l


In [75]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense , SimpleRNN
from tensorflow.keras.utils import to_categorical

In [ ]:
text = "Hello"
chars = sorted(set(text))

char_to_index = {c:i for i,c in enumerate(chars)}
index_to_char= {i:c for c,i in char_to_index.items()}

input_char = text[:-1]
target_char = text [1:]

In [79]:
input_index =[char_to_index[i] for i in  input_char ]
target_char = [char_to_index [i] for i in target_char]

In [81]:
X = to_categorical(input_index,num_classes =len(char))
X = np.reshape(X,(X.shape[0],1,X.shape[1]))
y = to_categorical(target_char,num_classes=len(char))

In [93]:
model = Sequential()
model.add(SimpleRNN(32,input_shape=(1,len(char)),return_sequences =False))
model.add(Dense(len(chars),activation='softmax'))

model.compile(loss='categorical_crossentropy',optimizer ='adam',metrics=['accuracy'])
model.summary()
model.fit(X,y,epochs=500)

Model: "sequential_24"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_28 (SimpleRNN)   (None, 32)                1184      
                                                                 
 dense_21 (Dense)            (None, 4)                 132       
                                                                 
Total params: 1,316
Trainable params: 1,316
Non-trainable params: 0
_________________________________________________________________
Epoch 1/500
1/1 [==============================] - 3s 3s/step - loss: 1.4204 - accuracy: 0.2500
Epoch 2/500
1/1 [==============================] - 0s 18ms/step - loss: 1.4100 - accuracy: 0.2500
Epoch 3/500
1/1 [==============================] - 0s 19ms/step - loss: 1.3997 - accuracy: 0.2500
Epoch 4/500
1/1 [==============================] - 0s 20ms/step - loss: 1.3894 - accuracy: 0.2500
Epoch 5/500
1/1 [==============================] - 0s 25m

In [6]:
import tensorflow as tf
import numpy as np 
from tensorflow.keras.layers import Dense,SimpleRNN
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical


In [9]:
text = 'Hello'
char = sorted(set(text))

char_to_index = {c:i for i,c in enumerate(char)}
index_to_char = {i:c for c,i in char_to_index.items()}

input_char = text[:-1]
target_char= text[1:]

input_index = [char_to_index[i] for i in input_char]
target_char = [char_to_index[i] for i in target_char]

X= to_categorical(input_index,num_classes=len(char))
X = np.reshape(X,(X.shape[0],1,X.shape[1]))
y = to_categorical(target_char,num_classes=len(char))

In [16]:
model = Sequential()
model.add(SimpleRNN(32,input_shape=(1,len(char)),return_sequences=False))
model.add(Dense(len(char),activation= 'softmax'))
model.compile(loss = 'categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()
model.fit(X,y,epochs=100)

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_5 (SimpleRNN)    (None, 32)                1184      
                                                                 
 dense_4 (Dense)             (None, 4)                 132       
                                                                 
Total params: 1,316
Trainable params: 1,316
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
1/1 [==============================] - 2s 2s/step - loss: 1.3107 - accuracy: 0.2500
Epoch 2/100
1/1 [==============================] - 0s 15ms/step - loss: 1.2999 - accuracy: 0.2500
Epoch 3/100
1/1 [==============================] - 0s 16ms/step - loss: 1.2893 - accuracy: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 17ms/step - loss: 1.2787 - accuracy: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 15ms